plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.compose.compiler)
}

android {
    namespace 'com.mulheres'
    compileSdk 37

    defaultConfig {
        applicationId "com.mulheres"
        minSdk 23
        targetSdk 37

        versionCode 33
        versionName "🌸33 (versão final)"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        vectorDrawables {
            useSupportLibrary true
        }
    }

    buildTypes {
        release {
            minifyEnabled true

            proguardFiles getDefaultProguardFile(
                    'proguard-android-optimize.txt'
            ),
            'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
    }
}

    buildFeatures {
        compose true
        viewBinding true
    }

    

    packaging {
        resources {
            excludes += '/META-INF/{AL2.0,LGPL2.1}'
        }
    }
}

dependencies {

    // AndroidX
    implementation 'androidx.core:core-ktx:1.13.1'
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.activity:activity-ktx:1.10.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
    implementation 'androidx.webkit:webkit:1.12.1'

    // Material
    implementation 'com.google.android.material:material:1.12.0'

    // Biometria
    implementation 'androidx.biometric:biometric:1.2.0-alpha05'

    // Localização
    implementation 'com.google.android.gms:play-services-location:21.3.0'

    // Segurança
    implementation 'androidx.security:security-crypto:1.1.0-alpha06'

    // Lifecycle
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.9.1'

    // Jetpack Compose
    implementation platform('androidx.compose:compose-bom:2024.09.00')

    implementation 'androidx.activity:activity-compose'
    implementation 'androidx.compose.ui:ui'
    implementation 'androidx.compose.ui:ui-graphics'
    implementation 'androidx.compose.ui:ui-tooling-preview'
    implementation 'androidx.compose.material3:material3'
    implementation 'androidx.lifecycle:lifecycle-runtime-compose'

    debugImplementation 'androidx.compose.ui:ui-tooling'
    debugImplementation 'androidx.compose.ui:ui-test-manifest'

    // ZIP4J
    implementation 'net.lingala.zip4j:zip4j:2.11.5'


    // Testes
    testImplementation 'junit:junit:4.13.2'

implementation("androidx.core:core-splashscreen:1.0.1")

    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'
    androidTestImplementation 'androidx.compose.ui:ui-test-junit4'
}