name: Data do primeiro commit da main

on:
  workflow_dispatch:

jobs:
  primeiro-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar todo o histórico
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Encontrar primeiro commit
        run: |
          PRIMEIRO=$(git rev-list --max-parents=0 HEAD | tail -n 1)
          DATA=$(git show -s --format=%cI "$PRIMEIRO")

          echo "Hash: $PRIMEIRO"
          echo "Data: $DATA"