name: 🌌 Observatório

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: write

jobs:
  observatorio:
    runs-on: ubuntu-24.04

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🔧 Dependências
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc imagemagick

      - name: 🧱 Compilar
        run: |
          gcc \
            -O2 \
            -Wall \
            -Wextra \
            tools/observatorio.c \
            -lm \
            -o observatorio

      - name: 🌌 Gerar observatório
        run: |
          ./observatorio

      - name: 🖼️ Converter para PNG
        run: |
          convert \
            docs/observatorio/observatorio.ppm \
            docs/observatorio/observatorio.png

          rm docs/observatorio/observatorio.ppm

      - name: 💾 Commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add docs/observatorio/observatorio.png

          if git diff --cached --quiet; then
            echo "Nenhuma alteração."
            exit 0
          fi

          git commit -m "chore: atualizar observatorio"
          git push