name: Testar o app usando o Android Emulator

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  testar:
    name: Testar no Android Emulator
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'

      - name: Dar permissão ao Gradle
        working-directory: Código-fonte do app
        run: chmod +x ./gradlew

      - name: Compilar APK de teste
        working-directory: Código-fonte do app
        run: ./gradlew assembleDebug

      - name: Testar no Android Emulator
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 35
          arch: x86_64
          profile: Pixel_6
          script: |
            adb install "Código-fonte do app/app/build/outputs/apk/debug/app-debug.apk"
            adb shell am start -n com.mulheres/.MainActivity
            sleep 10